# Generated by Django 2.2.3 on 2019-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
