# Generated by Django 2.2.3 on 2019-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabsindo',
            name='related',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vocabsindo',
            name='sinonim',
            field=models.TextField(null=True),
        ),
    ]
